// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYUdNUFREpi4V-WzfdUG-ceLaRVEDxD6I',
    appId: '1:267227106439:web:93639a5e105c791432bc22',
    messagingSenderId: '267227106439',
    projectId: 'chatapp-55cf9',
    authDomain: 'chatapp-55cf9.firebaseapp.com',
    databaseURL: 'https://chatapp-55cf9.firebaseio.com',
    storageBucket: 'chatapp-55cf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRso2bPNNOQGgDCJQfwt5aQCKoCfqklBg',
    appId: '1:267227106439:android:07ad6ff9c594074632bc22',
    messagingSenderId: '267227106439',
    projectId: 'chatapp-55cf9',
    databaseURL: 'https://chatapp-55cf9.firebaseio.com',
    storageBucket: 'chatapp-55cf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZdooY7OML54Ibqh-ZnlSzeWgV1sJfxIw',
    appId: '1:267227106439:ios:ad3df1046b357c0732bc22',
    messagingSenderId: '267227106439',
    projectId: 'chatapp-55cf9',
    databaseURL: 'https://chatapp-55cf9.firebaseio.com',
    storageBucket: 'chatapp-55cf9.appspot.com',
    androidClientId: '267227106439-6ugil8t93sdliv03lghff9rm7tk8oo5c.apps.googleusercontent.com',
    iosClientId: '267227106439-qbtb5bi4ev07r6pv3kb1342a8t1orn1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZdooY7OML54Ibqh-ZnlSzeWgV1sJfxIw',
    appId: '1:267227106439:ios:ad3df1046b357c0732bc22',
    messagingSenderId: '267227106439',
    projectId: 'chatapp-55cf9',
    databaseURL: 'https://chatapp-55cf9.firebaseio.com',
    storageBucket: 'chatapp-55cf9.appspot.com',
    androidClientId: '267227106439-6ugil8t93sdliv03lghff9rm7tk8oo5c.apps.googleusercontent.com',
    iosClientId: '267227106439-qbtb5bi4ev07r6pv3kb1342a8t1orn1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYUdNUFREpi4V-WzfdUG-ceLaRVEDxD6I',
    appId: '1:267227106439:web:7928f2111151439032bc22',
    messagingSenderId: '267227106439',
    projectId: 'chatapp-55cf9',
    authDomain: 'chatapp-55cf9.firebaseapp.com',
    databaseURL: 'https://chatapp-55cf9.firebaseio.com',
    storageBucket: 'chatapp-55cf9.appspot.com',
  );

}